references:
  docker_auth: &docker_auth
    auth:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_PASSWORD

  docker_image_ruby: &docker_image_ruby
    image: cimg/ruby:3.0.3
    <<: *docker_auth

  docker_container_ruby: &docker_container_ruby
    docker:
      - *docker_image_ruby
      - image: redis
        <<: *docker_auth
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        environment:
          - cluster.name: elasticsearch
          - transport.host: localhost
          - network.host: 127.0.0.1
          - http.port: 9200
          - discovery.type: single-node
          - xpack.security.enabled: false
        command:
          - sh
          - -c
          - "bin/elasticsearch-plugin install analysis-kuromoji analysis-smartcn analysis-stempel analysis-ukrainian;
             /usr/local/bin/docker-entrypoint.sh elasticsearch"
    working_directory: ~/repo

version: 2.1

jobs:
  build:
    <<: *docker_container_ruby

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Wait for services
          command: |
            dockerize -wait tcp://localhost:6379 -timeout 1m
            dockerize -wait tcp://localhost:9200 -timeout 1m

      - run:
          name: Configure Bundler
          command: |
            export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")
            gem install bundler -v $BUNDLER_VERSION

      - run:
          name: Install gems
          command: bundle install --jobs=4 --retry=3

      - run:
          name: Run Ruby tests
          command: bundle exec rake test

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results